version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - '5432:5432'
    volumes: 
      - db:/opt/postgresql/data
  web:
    image: "periodic-puller:latest"
  puller:
    image: "data-warden-web:latest"
    ports:
      - "8001:8001"
volumes:
  db:
    driver: local